export const CAPITAL_CITY = [
  'Kabul',
  'Tirana',
  'Algiers',
  'Andorra la Vella',
  'Luanda',
  "Saint John's",
  'Buenos Aires',
  'Yerevan',
  'Canberra',
  'Vienna',
  'Baku',
  'Nassau',
  'Manama',
  'Dhaka',
  'Bridgetown',
  'Minsk',
  'Brussels',
  'Belmopan',
  'Porto-Novo',
  'Thimphu',
  'La Paz',
  'Sarajevo',
  'Gaborone',
  'Brasília',
  'Bandar Seri Begawan',
  'Sofia',
  'Ouagadougou',
  'Bujumbura',
  'Phnom Penh',
  'Yaoundé',
  'Ottawa',
  'Praia',
  'Bangui',
  "N'Djamena",
  'Santiago',
  'Beijing',
  'Bogotá',
  'Moroni',
  'Kinshasa',
  'Brazzaville',
  'San José',
  'Zagreb',
  'Havana',
  'Nicosia',
  'Prague',
  'Copenhagen',
  'Djibouti',
  'Roseau',
  'Santo Domingo',
  'Quito',
  'Cairo',
  'San Salvador',
  'Malabo',
  'Asmara',
  'Tallinn',
  'Addis Ababa',
  'Suva',
  'Helsinki',
  'Paris',
  'Libreville',
  'Banjul',
  'Tbilisi',
  'Berlin',
  'Accra',
  'Athens',
  "St. George's",
  'Guatemala City',
  'Conakry',
  'Bissau',
  'Georgetown',
  'Port-au-Prince',
  'Tegucigalpa',
  'Budapest',
  'Reykjavik',
  'New Delhi',
  'Jakarta',
  'Tehran',
  'Baghdad',
  'Dublin',
  'Jerusalem',
  'Rome',
  'Kingston',
  'Tokyo',
  'Amman',
  'Nur-Sultan',
  'Nairobi',
  'Tarawa',
  'Pristina',
  'Kuwait City',
  'Bishkek',
  'Vientiane',
  'Riga',
  'Beirut',
  'Maseru',
  'Monrovia',
  'Tripoli',
  'Vaduz',
  'Vilnius',
  'Luxembourg City',
  'Skopje',
  'Antananarivo',
  'Lilongwe',
  'Kuala Lumpur',
  'Male',
  'Bamako',
  'Valletta',
  'Majuro',
  'Nouakchott',
  'Port Louis',
  'Mexico City',
  'Palikir',
  'Chisinau',
  'Monaco',
  'Ulaanbaatar',
  'Podgorica',
  'Rabat',
  'Maputo',
  'Naypyidaw',
  'Windhoek',
  'Yaren',
  'Kathmandu',
  'Amsterdam',
  'Wellington',
  'Managua',
  'Niamey',
  'Abuja',
  'Oslo',
  'Muscat',
  'Islamabad',
  'Ngerulmud',
  'Jerusalem',
  'Panama City',
  'Port Moresby',
  'Asunción',
  'Lima',
  'Manila',
  'Warsaw',
  'Lisbon',
  'Doha',
  'Bucharest',
  'Moscow',
  'Kigali',
  'Basseterre',
  'Castries',
  'Kingstown',
  'Apia',
  'San Marino',
  'São Tomé',
  'Riyadh',
  'Dakar',
  'Belgrade',
  'Victoria',
  'Freetown',
  'Singapore',
  'Bratislava',
  'Ljubljana',
  'Honiara',
  'Mogadishu',
  'Pretoria',
  'Juba',
  'Madrid',
  'Colombo',
  'Khartoum',
  'Paramaribo',
  'Stockholm',
  'Bern',
  'Damascus',
  'Taipei',
  'Dushanbe',
  'Dodoma',
  'Bangkok',
  'Dili',
  'Lomé',
  "Nuku'alofa",
  'Port of Spain',
  'Tunis',
  'Ankara',
  'Ashgabat',
  'Funafuti',
  'Kampala',
  'Kyiv',
  'Abu Dhabi',
  'London',
  'Washington, D.C.',
  'Montevideo',
  'Tashkent',
  'Port Vila',
  'Vatican City',
  'Caracas',
  'Hanoi',
  "Sana'a",
  'Lusaka',
  'Harare',
];

export const COUNTRY_CAPITALS = {
  Japan: 'Tokyo',
  'The Philippines': 'Manila',
  'United States': 'Washington, D.C.',
  Canada: 'Ottawa',
  Australia: 'Canberra',
  Brazil: 'Brasília',
  Russia: 'Moscow',
  China: 'Beijing',
  India: 'New Delhi',
  'United Kingdom': 'London',
  France: 'Paris',
  Germany: 'Berlin',
  Italy: 'Rome',
  'South Korea': 'Seoul',
  Spain: 'Madrid',
  Mexico: 'Mexico City',
  Argentina: 'Buenos Aires',
  Egypt: 'Cairo',
  Nigeria: 'Abuja',
  'South Africa': 'Pretoria',
  Turkey: 'Ankara',
  Iran: 'Tehran',
  'Saudi Arabia': 'Riyadh',
  Indonesia: 'Jakarta',
  Pakistan: 'Islamabad',
  Bangladesh: 'Dhaka',
  Vietnam: 'Hanoi',
  Thailand: 'Bangkok',
  Malaysia: ['Kuala Lumpur', 'Putrajaya'],
  Philippines: 'Manila',
  Singapore: 'Singapore',
  Cambodia: 'Phnom Penh',
  Myanmar: 'Naypyidaw',
  Laos: 'Vientiane',
  Brunei: 'Bandar Seri Begawan',
  'Timor-Leste': 'Dili',
  Afghanistan: 'Kabul',
  Iraq: 'Baghdad',
  Jordan: 'Amman',
  Lebanon: 'Beirut',
  Syria: 'Damascus',
  Israel: 'Jerusalem',
  Palestine: 'Ramallah',
  Qatar: 'Doha',
  Kuwait: 'Kuwait City',
  Bahrain: 'Manama',
  Oman: 'Muscat',
  'United Arab Emirates': 'Abu Dhabi',
  Yemen: "Sana'a",
  'Sri Lanka': 'Colombo',
  Nepal: 'Kathmandu',
  Maldives: 'Male',
  Bhutan: 'Thimphu',
  Mongolia: 'Ulaanbaatar',
  Kazakhstan: 'Nur-Sultan',
  Kyrgyzstan: 'Bishkek',
  Tajikistan: 'Dushanbe',
  Uzbekistan: 'Tashkent',
  Turkmenistan: 'Ashgabat',
  Georgia: 'Tbilisi',
  Armenia: 'Yerevan',
  Azerbaijan: 'Baku',
};
